ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'INTAKE';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'READY';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'QA';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'WAITING';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'REWORK';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "WorkboardColumnType" ADD VALUE IF NOT EXISTS 'ARCHIVED';
